feed/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView
from django.conf import settings
from django.conf.urls.static import static
app_name = 'feed'

urlpatterns = [

    path('', HomePageView.as_view(), name='index'),
    path('info/<int:pk>/', PostDetailView.as_view(), name="detail"),
    path('post/', AddPostView.as_view(), name='post'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

from feed import urls as feed_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace='feed'))
]

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField
# Create your models here.


class Post(models.Model):
    text = models.CharField(max_length=140, blank=False, null=False)
    image = ImageField()

    def __str__(self):
        return self.text

feed/forms.py
from django import forms


class PostForm(forms.Form):
    text = forms.CharField()
    image = forms.FileField()

feed/views.py
from django.views.generic import TemplateView, DetailView, FormView
from django.contrib import messages
from .forms import PostForm
from .models import Post


class HomePageView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all().order_by('-id')
        return context


class PostDetailView(DetailView):
    template_name = "detail.html"
    model = Post


class AddPostView(FormView):
    template_name = "new_post.html"
    form_class = PostForm
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        new_object = Post.objects.create(
            text=form.cleaned_data['text'],
            image=form.cleaned_data['image']
        )
        messages.add_message(self.request, messages.SUCCESS,
                            'Your post was successful.')
        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Default title{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>

  <body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}


    {% block body %}{% endblock %}
  </body>
</html>

templates/detail.html
{% extends "base.html" %}

{% block title %}Detail view{% endblock %}

{% block body %}
    <a href="{% url 'feed:index' %}" ><- Go back</a>
    <h3>Text</h3>
    {{object.text}}

    <h3>Image</h3>
    <img src='{{object.image.url}}' style='width: 100%; height: auto;'>
{% endblock %}

templates/home.html
{% extends "base.html" %} 
{% load thumbnail %}

{% block title %}Home page{% endblock %} 

{% block body %} 

    <a href="{% url 'feed:post' %}">Add a new post &rarr;</a>
    <hr>
    {% for post in posts %}
    <a href="{% url 'feed:detail' post.id %}">More details</a>
        {{ post.text }} <br>

        {% thumbnail post.image "100x100" crop="center" as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
        {% endthumbnail %}
        <hr>
    {% endfor %}

{% endblock %}

templates/new_post.html
{% extends "base.html" %}

{% block title %}Upload a new image{% endblock %}

{% block body %}
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <div>
            <button type="submit">Submit form</button>
        </div>
    </form>
{% endblock %}